#!/usr/bin/env python3
"""
Anthropic Synthesis Provider — Wave 91 Action A.

Wraps the deterministic mock-provider drafts produced by
:mod:`Trainforge.generators.instruction_factory` and
:mod:`Trainforge.generators.preference_factory` in a Claude paraphrase
+ verify pass. The mock drafts are already grounded in chunk metadata
(key_terms, concept_tags, misconceptions, learning_outcome_refs); the
LLM step only paraphrases — it must NOT introduce facts the chunk
text does not support.

Rationale: Wave 90 shipped the trainer. Running it on the existing
mock-only synthesis output would train a template-recognizer because
the templates are deterministic and only ~30 stems wide. This provider
introduces lexical and stylistic diversity while preserving the
factual content drawn from the chunk.

Design constraints:

- Fail loud: ``ANTHROPIC_API_KEY`` missing → ``RuntimeError``. Never
  silently fall back to the mock pair.
- Prompt caching: the (system prompt + chunk text) prefix is wrapped
  in ``cache_control: {"type": "ephemeral"}`` so subsequent calls on
  the same chunk hit the cache (matches the
  ``Trainforge/align_chunks.py`` pattern).
- Decision capture: every call site emits one
  ``synthesis_provider_call`` decision with rationale that interpolates
  provider, model, chunk_id, draft length, and response token counts.
- Retry: malformed JSON gets up to 3 retries before raising
  ``RuntimeError``. We don't retry on transport errors here — that's
  the caller's job (``run_synthesis`` already has a poison-pill loop).

Default model: ``claude-sonnet-4-6``. Override via the
``ANTHROPIC_SYNTHESIS_MODEL`` env var.
"""

from __future__ import annotations

import json
import logging
import os
import re
from dataclasses import dataclass
from typing import Any, Dict, Optional

logger = logging.getLogger(__name__)


DEFAULT_SYNTHESIS_MODEL = "claude-sonnet-4-6"
ENV_API_KEY = "ANTHROPIC_API_KEY"
ENV_MODEL = "ANTHROPIC_SYNTHESIS_MODEL"

# Hard cap on retry attempts when the model returns malformed JSON.
MAX_PARSE_RETRIES = 10

# Length sentinels — match instruction_factory.py / preference_factory.py
# so paraphrased output respects the same downstream gates.
PROMPT_MIN, PROMPT_MAX = 40, 400
COMPLETION_MIN, COMPLETION_MAX = 50, 600

# Per-`kind` length bounds, used by ``_clamp`` to look up [lo, hi] without
# the call site having to thread the bounds through. The ``chosen`` and
# ``rejected`` arms of a preference pair share the completion bounds.
_KIND_BOUNDS: Dict[str, tuple] = {
    "prompt": (PROMPT_MIN, PROMPT_MAX),
    "completion": (COMPLETION_MIN, COMPLETION_MAX),
    "chosen": (COMPLETION_MIN, COMPLETION_MAX),
    "rejected": (COMPLETION_MIN, COMPLETION_MAX),
}


# ---------------------------------------------------------------------------
# Errors
# ---------------------------------------------------------------------------


class SynthesisProviderError(RuntimeError):
    """Typed error raised on synthesis-provider validation failures.

    Wave 112 Task 2: replaces the prior sentinel-injection branch in
    ``_clamp`` (which silently appended a hardcoded filler phrase to any
    short paraphrase, poisoning training data with a sentinel parrot
    pattern). Raising a typed error instead lets the caller's retry path
    fire and forces a re-paraphrase.

    The ``code`` field is a stable string the caller can dispatch on
    (e.g. ``completion_below_minimum``, ``prompt_below_minimum``);
    ``chunk_id`` is optional context for log/audit correlation.
    """

    def __init__(
        self,
        message: str,
        *,
        code: Optional[str] = None,
        chunk_id: Optional[str] = None,
    ) -> None:
        super().__init__(message)
        self.code = code
        self.chunk_id = chunk_id


# ---------------------------------------------------------------------------
# System prompt fragments
# ---------------------------------------------------------------------------

_INSTRUCTION_SYSTEM_PROMPT = (
    "You are a paraphrase-and-verify assistant for instruction-tuning data. "
    "You receive a draft (prompt, completion) pair generated by a deterministic "
    "template, plus the chunk text the pair was grounded in. Your job is to "
    "rewrite the prompt and completion so they read naturally and vary lexically, "
    "WITHOUT introducing any fact, claim, term, or example that does not appear "
    "in the chunk text. If the draft is already faithful, paraphrase it; never "
    "fabricate. Preserve the cognitive level (Bloom's) of the original. Return "
    "ONLY a single valid JSON object with keys 'prompt' and 'completion' — no "
    "preamble, no markdown fences, no commentary."
)

_PREFERENCE_SYSTEM_PROMPT = (
    "You are a paraphrase-and-verify assistant for preference-tuning data (DPO). "
    "You receive a draft (prompt, chosen, rejected) triple plus the chunk text. "
    "Rewrite all three so they read naturally and vary lexically, WITHOUT "
    "introducing any fact not in the chunk. The 'chosen' completion must remain "
    "factually correct; the 'rejected' completion must remain plausibly wrong "
    "(a misconception or weak answer) so the preference signal is preserved. "
    "Return ONLY a single valid JSON object with keys 'prompt', 'chosen', and "
    "'rejected' — no preamble, no markdown fences, no commentary."
)


# ---------------------------------------------------------------------------
# Result types
# ---------------------------------------------------------------------------


@dataclass
class _Usage:
    """Token-usage tally extracted from the Anthropic response."""

    input_tokens: int = 0
    output_tokens: int = 0
    cache_read_tokens: int = 0
    cache_creation_tokens: int = 0

    def as_dict(self) -> Dict[str, int]:
        return {
            "input_tokens": self.input_tokens,
            "output_tokens": self.output_tokens,
            "cache_read_tokens": self.cache_read_tokens,
            "cache_creation_tokens": self.cache_creation_tokens,
        }


# ---------------------------------------------------------------------------
# Provider class
# ---------------------------------------------------------------------------


class AnthropicSynthesisProvider:
    """Paraphrases mock-provider drafts via the Anthropic SDK.

    Constructor resolves the API key from the ``ANTHROPIC_API_KEY``
    environment variable. The model defaults to ``claude-sonnet-4-6``
    and can be overridden either via the ``ANTHROPIC_SYNTHESIS_MODEL``
    env var or the ``model`` kwarg. The Anthropic ``Client`` itself is
    lazily instantiated (and lazily imported) the first time a
    paraphrase method is called.
    """

    def __init__(
        self,
        *,
        api_key: Optional[str] = None,
        model: Optional[str] = None,
        client: Optional[Any] = None,
        capture: Optional[Any] = None,
    ) -> None:
        resolved_key = api_key or os.environ.get(ENV_API_KEY)
        if client is None and not resolved_key:
            raise RuntimeError(
                f"{ENV_API_KEY} required for provider=anthropic; "
                "set the env var or inject a client (tests)."
            )
        self._api_key = resolved_key
        self._model = (
            model
            or os.environ.get(ENV_MODEL)
            or DEFAULT_SYNTHESIS_MODEL
        )
        self._client = client
        self._capture = capture

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def paraphrase_instruction(
        self, draft: Dict[str, Any], chunk: Dict[str, Any]
    ) -> Dict[str, Any]:
        """Paraphrase a draft instruction pair against its chunk.

        Args:
            draft: Mock-provider output with keys ``prompt`` and
                ``completion`` (other metadata is preserved unchanged).
            chunk: The enriched chunk the draft was synthesized from.
                Used to anchor the paraphrase against the source text
                via prompt caching.

        Returns:
            A new dict with the same keys as ``draft`` plus
            ``prompt`` / ``completion`` rewritten by Claude. All other
            metadata fields (chunk_id, lo_refs, bloom_level, content_type,
            seed, template_id, schema_version, etc.) are preserved.

        Raises:
            RuntimeError: After ``MAX_PARSE_RETRIES`` malformed JSON
                responses, or when the Anthropic SDK is not installed.
        """
        if not isinstance(draft, dict):
            raise TypeError("draft must be a dict")
        chunk_id = str(chunk.get("id") or chunk.get("chunk_id") or "")
        chunk_text = str(chunk.get("text") or "")
        user_prompt = self._render_instruction_user(draft, chunk_id)

        parsed, usage = self._call_with_parse(
            system_prompt=_INSTRUCTION_SYSTEM_PROMPT,
            chunk_text=chunk_text,
            user_prompt=user_prompt,
            required_keys=("prompt", "completion"),
        )

        out = dict(draft)
        out["prompt"] = self._clamp(
            parsed["prompt"], kind="prompt", chunk_id=chunk_id
        )
        out["completion"] = self._clamp(
            parsed["completion"], kind="completion", chunk_id=chunk_id
        )
        out["provider"] = "anthropic"

        self._emit_decision(
            kind="instruction",
            draft=draft,
            chunk_id=chunk_id,
            usage=usage,
        )
        return out

    def paraphrase_preference(
        self, draft: Dict[str, Any], chunk: Dict[str, Any]
    ) -> Dict[str, Any]:
        """Paraphrase a draft preference triple against its chunk.

        Args:
            draft: Mock-provider output with keys ``prompt``,
                ``chosen``, ``rejected``.
            chunk: Enriched source chunk.

        Returns:
            New dict with ``prompt`` / ``chosen`` / ``rejected``
            rewritten by Claude. Other fields preserved.
        """
        if not isinstance(draft, dict):
            raise TypeError("draft must be a dict")
        chunk_id = str(chunk.get("id") or chunk.get("chunk_id") or "")
        chunk_text = str(chunk.get("text") or "")
        user_prompt = self._render_preference_user(draft, chunk_id)

        parsed, usage = self._call_with_parse(
            system_prompt=_PREFERENCE_SYSTEM_PROMPT,
            chunk_text=chunk_text,
            user_prompt=user_prompt,
            required_keys=("prompt", "chosen", "rejected"),
        )

        out = dict(draft)
        out["prompt"] = self._clamp(
            parsed["prompt"], kind="prompt", chunk_id=chunk_id
        )
        out["chosen"] = self._clamp(
            parsed["chosen"], kind="chosen", chunk_id=chunk_id
        )
        out["rejected"] = self._clamp(
            parsed["rejected"], kind="rejected", chunk_id=chunk_id
        )
        out["provider"] = "anthropic"

        self._emit_decision(
            kind="preference",
            draft=draft,
            chunk_id=chunk_id,
            usage=usage,
        )
        return out

    # ------------------------------------------------------------------
    # Internals
    # ------------------------------------------------------------------

    @property
    def client(self) -> Any:
        if self._client is None:
            try:
                import anthropic  # noqa: PLC0415 — lazy by design
            except ImportError as exc:  # pragma: no cover — covered via mocks
                raise RuntimeError(
                    "anthropic package required for AnthropicSynthesisProvider. "
                    "Install with: pip install anthropic"
                ) from exc
            self._client = anthropic.Anthropic(api_key=self._api_key)
        return self._client

    def _build_system_blocks(
        self, system_prompt: str, chunk_text: str
    ) -> Any:
        """Build the cached system prompt block list.

        The system prompt + chunk text together form the cache prefix.
        We mark the LAST system block with ``cache_control: ephemeral``
        so the SDK caches everything up to and including it, per
        Anthropic's prompt-caching contract.
        """
        return [
            {
                "type": "text",
                "text": system_prompt,
            },
            {
                "type": "text",
                "text": "Source chunk text:\n\n" + chunk_text,
                "cache_control": {"type": "ephemeral"},
            },
        ]

    def _call_with_parse(
        self,
        *,
        system_prompt: str,
        chunk_text: str,
        user_prompt: str,
        required_keys: tuple,
    ) -> tuple:
        """Issue the SDK call and parse the JSON response, retrying on
        malformed JSON up to ``MAX_PARSE_RETRIES`` times."""
        system_blocks = self._build_system_blocks(system_prompt, chunk_text)
        attempts = 0
        last_err: Optional[Exception] = None
        last_text: str = ""
        while attempts < MAX_PARSE_RETRIES:
            attempts += 1
            response = self.client.messages.create(
                model=self._model,
                max_tokens=1024,
                system=system_blocks,
                messages=[{"role": "user", "content": user_prompt}],
            )
            text = self._extract_text(response)
            last_text = text
            try:
                parsed = self._parse_json(text)
            except ValueError as exc:
                last_err = exc
                logger.warning(
                    "anthropic synthesis: parse retry %d/%d: %s",
                    attempts, MAX_PARSE_RETRIES, exc,
                )
                continue
            missing = [k for k in required_keys if k not in parsed]
            if missing:
                last_err = ValueError(
                    f"response missing required keys: {missing}"
                )
                continue
            return parsed, self._extract_usage(response)
        # H4: typed exception parity with LocalSynthesisProvider so the
        # caller's recovery branch (paraphrase-exhaustion soft-skip in
        # ``run_synthesis``) doesn't have to dispatch on provider. The
        # ``code`` value matches ``_local_provider.py``'s exhaustion path
        # exactly. Original parse cause preserved via ``__cause__`` so
        # postmortem audits keep the underlying parse trace.
        raise SynthesisProviderError(
            f"AnthropicSynthesisProvider: failed to parse a valid JSON "
            f"response after {MAX_PARSE_RETRIES} attempts. "
            f"Last error: {last_err}; tail of last response: {last_text[-200:]!r}",
            code="paraphrase_invalid_after_retry",
        ) from last_err

    @staticmethod
    def _render_instruction_user(
        draft: Dict[str, Any], chunk_id: str
    ) -> str:
        return (
            f"Chunk ID: {chunk_id}\n"
            f"Bloom level: {draft.get('bloom_level','unknown')}\n"
            f"Content type: {draft.get('content_type','unknown')}\n"
            f"Template ID: {draft.get('template_id','unknown')}\n"
            f"\n"
            f"Draft prompt:\n{draft.get('prompt','')}\n"
            f"\n"
            f"Draft completion:\n{draft.get('completion','')}\n"
            f"\n"
            f"Rewrite the prompt and completion. Return JSON with keys "
            f"'prompt' and 'completion'."
        )

    @staticmethod
    def _render_preference_user(
        draft: Dict[str, Any], chunk_id: str
    ) -> str:
        return (
            f"Chunk ID: {chunk_id}\n"
            f"Source: {draft.get('rejected_source','unknown')}\n"
            f"\n"
            f"Draft prompt:\n{draft.get('prompt','')}\n"
            f"\n"
            f"Draft chosen:\n{draft.get('chosen','')}\n"
            f"\n"
            f"Draft rejected:\n{draft.get('rejected','')}\n"
            f"\n"
            f"Rewrite all three. Return JSON with keys 'prompt', "
            f"'chosen', and 'rejected'."
        )

    @staticmethod
    def _extract_text(response: Any) -> str:
        """Extract concatenated text from an Anthropic ``Message``.

        Mock objects in tests pass dicts; production SDK passes typed
        objects. Handle both.
        """
        content = getattr(response, "content", None)
        if content is None and isinstance(response, dict):
            content = response.get("content")
        if content is None:
            return ""
        text_parts = []
        for block in content:
            block_type = getattr(block, "type", None) or (
                block.get("type") if isinstance(block, dict) else None
            )
            if block_type != "text":
                continue
            t = getattr(block, "text", None) or (
                block.get("text") if isinstance(block, dict) else None
            )
            if t:
                text_parts.append(str(t))
        return "".join(text_parts)

    @staticmethod
    def _extract_usage(response: Any) -> _Usage:
        usage = getattr(response, "usage", None) or (
            response.get("usage") if isinstance(response, dict) else None
        )
        if usage is None:
            return _Usage()
        # Both SDK objects and dicts.
        def _g(name: str) -> int:
            v = getattr(usage, name, None)
            if v is None and isinstance(usage, dict):
                v = usage.get(name)
            try:
                return int(v) if v is not None else 0
            except (TypeError, ValueError):
                return 0
        return _Usage(
            input_tokens=_g("input_tokens"),
            output_tokens=_g("output_tokens"),
            cache_read_tokens=_g("cache_read_input_tokens"),
            cache_creation_tokens=_g("cache_creation_input_tokens"),
        )

    @staticmethod
    def _parse_json(text: str) -> Dict[str, Any]:
        """Tolerant JSON parser. Strips a single ```json fence wrapper
        when present; otherwise scans for the first balanced JSON object."""
        if not text or not text.strip():
            raise ValueError("empty response text")
        s = text.strip()
        # Strip ```json ... ``` fence if present.
        fence = re.match(r"^```(?:json)?\s*(.*?)\s*```$", s, re.DOTALL)
        if fence:
            s = fence.group(1).strip()
        # Try direct decode first.
        try:
            return json.loads(s)
        except json.JSONDecodeError:
            pass
        # Fallback: locate first {...} balanced span.
        start = s.find("{")
        if start < 0:
            raise ValueError("no JSON object in response")
        depth = 0
        for i, ch in enumerate(s[start:], start=start):
            if ch == "{":
                depth += 1
            elif ch == "}":
                depth -= 1
                if depth == 0:
                    candidate = s[start:i + 1]
                    return json.loads(candidate)
        raise ValueError("unbalanced JSON object in response")

    @staticmethod
    def _clamp(text: str, kind: str, *, chunk_id: Optional[str] = None) -> str:
        """Clamp paraphrased text to the [lo, hi] bounds for ``kind``.

        Wave 112 Task 2: short responses now raise
        ``SynthesisProviderError`` rather than being padded with a
        hardcoded sentinel phrase. The upper-bound truncation behavior
        (preserving sentence boundaries when possible) is unchanged.

        Args:
            text: Paraphrased text from the LLM.
            kind: One of ``prompt``, ``completion``, ``chosen``,
                ``rejected``. Selects the [lo, hi] bounds.
            chunk_id: Optional context for the raised error / audit log.

        Raises:
            SynthesisProviderError: When the stripped text is below the
                minimum length for ``kind``. ``code`` is set to
                ``"{kind}_below_minimum"`` so the caller can dispatch.
            ValueError: When ``kind`` is not a recognized bound key.
        """
        try:
            lo, hi = _KIND_BOUNDS[kind]
        except KeyError as exc:
            raise ValueError(
                f"_clamp: unknown kind={kind!r}; expected one of "
                f"{sorted(_KIND_BOUNDS)}"
            ) from exc
        s = (text or "").strip()
        if len(s) < lo:
            raise SynthesisProviderError(
                f"{kind} length {len(s)} below minimum {lo}; refusing to "
                f"inject sentinel filler. Caller should retry the paraphrase.",
                code=f"{kind}_below_minimum",
                chunk_id=chunk_id,
            )
        if len(s) > hi:
            hard = s[:hi]
            period = hard.rfind(". ")
            if period > lo:
                s = hard[: period + 1]
            else:
                s = hard.rstrip() + "..."
        return s

    def _emit_decision(
        self,
        *,
        kind: str,
        draft: Dict[str, Any],
        chunk_id: str,
        usage: _Usage,
    ) -> None:
        if self._capture is None:
            return
        try:
            self._capture.log_decision(
                decision_type="synthesis_provider_call",
                decision=(
                    f"Anthropic paraphrase ({kind}) for chunk {chunk_id} "
                    f"using model {self._model}; "
                    f"input_tokens={usage.input_tokens}, "
                    f"output_tokens={usage.output_tokens}, "
                    f"cache_read={usage.cache_read_tokens}."
                ),
                rationale=(
                    f"Paraphrasing template-generated {kind} draft "
                    f"(template_id={draft.get('template_id','n/a')}, "
                    f"draft_prompt_len={len(str(draft.get('prompt','')))}, "
                    f"chunk_id={chunk_id}) to add lexical and stylistic "
                    f"diversity beyond the deterministic mock catalog. "
                    f"Cache_control on chunk-text system block keeps "
                    f"per-chunk cost roughly O(output_tokens={usage.output_tokens})."
                ),
            )
        except Exception as exc:  # pragma: no cover — defensive
            logger.warning("synthesis_provider_call capture failed: %s", exc)


__all__ = [
    "AnthropicSynthesisProvider",
    "DEFAULT_SYNTHESIS_MODEL",
    "SynthesisProviderError",
    "PROMPT_MIN",
    "PROMPT_MAX",
    "COMPLETION_MIN",
    "COMPLETION_MAX",
]
