#!/usr/bin/env python3
"""Together AI synthesis provider — Wave 113 prep.

Wraps the deterministic mock-provider drafts produced by
:mod:`Trainforge.generators.instruction_factory` and
:mod:`Trainforge.generators.preference_factory` in an OSS-teacher
paraphrase + verify pass. Routes through Together AI's OpenAI-compatible
chat-completions endpoint, which (unlike Anthropic's ToS) explicitly
permits using the model output as training data for another model. This
is the ToS-clean teacher pass for SLM training-data generation.

Default model: ``meta-llama/Llama-3.3-70B-Instruct-Turbo``. Override via
``TOGETHER_SYNTHESIS_MODEL`` (e.g. ``Qwen/Qwen2.5-72B-Instruct-Turbo``,
``deepseek-ai/DeepSeek-V3``).

Mirrors :class:`AnthropicSynthesisProvider`:

- Same public surface: ``paraphrase_instruction`` / ``paraphrase_preference``.
- Same length-clamp invariant (Wave 112): short paraphrases raise
  ``SynthesisProviderError`` rather than getting padded with sentinel
  filler; over-max strings get truncated on a sentence boundary.
- Same ``synthesis_provider_call`` decision-capture event per call,
  with a rationale that interpolates the chunk_id, model, retry count,
  and token counts (≥20 chars per the project's LLM call-site
  instrumentation contract).
- Output ``provider`` field is ``"together"``.

Differences from the Anthropic provider:

- HTTP-driven (``httpx`` + bearer auth); no SDK install required.
- Retry policy: transient HTTP failures (429 / 503) are retried with
  exponential backoff up to ``MAX_HTTP_RETRIES`` attempts. Other 4xx
  surface immediately as ``SynthesisProviderError(code=str(status))``.
- No prompt-caching API on Together — chunk text is sent on every
  request, accepted as a per-call cost.
"""

from __future__ import annotations

import logging
import os
import time
from typing import Any, Dict, Optional

import httpx

from Trainforge.generators._anthropic_provider import (  # noqa: F401
    COMPLETION_MAX,
    COMPLETION_MIN,
    PROMPT_MAX,
    PROMPT_MIN,
    SynthesisProviderError,
    _KIND_BOUNDS,
)

logger = logging.getLogger(__name__)


DEFAULT_SYNTHESIS_MODEL = "meta-llama/Llama-3.3-70B-Instruct-Turbo"
DEFAULT_BASE_URL = "https://api.together.xyz/v1"
# Backwards-compat alias for callers that imported the full URL constant
# directly. Kept identical to the legacy hard-coded value so existing tests
# keep matching against ``str(req.url) == TOGETHER_API_URL``.
TOGETHER_API_URL = "https://api.together.xyz/v1/chat/completions"
ENV_API_KEY = "TOGETHER_API_KEY"
ENV_MODEL = "TOGETHER_SYNTHESIS_MODEL"
# Wave 113: the Together provider doesn't accept a base-URL env override.
# Kept None so subclasses that DO want one (e.g. ``LocalSynthesisProvider``
# whose server URL varies per Ollama / vLLM / llama.cpp / LM Studio install)
# can flip it to a real env-var name without touching the base class.
ENV_BASE_URL: Optional[str] = None

# Hard cap on retry attempts when the endpoint returns a transient error.
MAX_HTTP_RETRIES = 3
# Hard cap on retry attempts when the model returns malformed JSON.
MAX_PARSE_RETRIES = 3
# Default per-call HTTP timeout (seconds).
DEFAULT_TIMEOUT = 60.0
# Initial backoff in seconds; doubled per retry.
INITIAL_BACKOFF_SECONDS = 1.0
# Status codes we treat as transient and retry.
_RETRYABLE_STATUS = frozenset({429, 500, 502, 503, 504})


# ---------------------------------------------------------------------------
# System prompt fragments — reused from the Anthropic provider's contract
# so paraphrased output stays interchangeable across providers.
# ---------------------------------------------------------------------------

_INSTRUCTION_SYSTEM_PROMPT = (
    "You are a paraphrase-and-verify assistant for instruction-tuning data. "
    "You receive a draft (prompt, completion) pair generated by a deterministic "
    "template, plus the chunk text the pair was grounded in. Your job is to "
    "rewrite the prompt and completion so they read naturally and vary lexically, "
    "WITHOUT introducing any fact, claim, term, or example that does not appear "
    "in the chunk text. If the draft is already faithful, paraphrase it; never "
    "fabricate. Preserve the cognitive level (Bloom's) of the original. Return "
    "ONLY a single valid JSON object with keys 'prompt' and 'completion' — no "
    "preamble, no markdown fences, no commentary."
)

_PREFERENCE_SYSTEM_PROMPT = (
    "You are a paraphrase-and-verify assistant for preference-tuning data (DPO). "
    "You receive a draft (prompt, chosen, rejected) triple plus the chunk text. "
    "Rewrite all three so they read naturally and vary lexically, WITHOUT "
    "introducing any fact not in the chunk. The 'chosen' completion must remain "
    "factually correct; the 'rejected' completion must remain plausibly wrong "
    "(a misconception or weak answer) so the preference signal is preserved. "
    "Return ONLY a single valid JSON object with keys 'prompt', 'chosen', and "
    "'rejected' — no preamble, no markdown fences, no commentary."
)


# ---------------------------------------------------------------------------
# Provider class
# ---------------------------------------------------------------------------


class TogetherSynthesisProvider:
    """Paraphrases mock-provider drafts via Together AI's hosted OSS models.

    Constructor resolves the API key from the ``TOGETHER_API_KEY``
    environment variable when ``api_key`` isn't passed. Model defaults to
    ``meta-llama/Llama-3.3-70B-Instruct-Turbo`` and is overridable via
    the ``TOGETHER_SYNTHESIS_MODEL`` env var or the ``model`` kwarg.

    The HTTP client is owned by the provider and can be supplied via the
    ``client`` kwarg (tests inject one with ``httpx.MockTransport``).

    Subclass hooks (Wave 113 prep — used by
    :class:`Trainforge.generators._local_provider.LocalSynthesisProvider`):

    - ``_default_base_url``: provider-specific OpenAI-compatible base URL
      (the ``/chat/completions`` suffix is appended at request time).
    - ``_default_model``: short / repo-style model identifier.
    - ``_default_api_key_env`` / ``_default_model_env`` /
      ``_default_base_url_env``: env var names the constructor reads to
      populate the resolved value when no explicit kwarg is supplied.
      ``None`` for ``_default_base_url_env`` (the Together case) means
      the base URL isn't env-overridable on this provider.
    - ``_api_key_required``: when ``False``, the constructor accepts
      callers that didn't set the API-key env var and didn't inject a
      client — needed for local model servers that ignore auth.
    - ``_provider_name``: string written to ``out["provider"]`` on every
      emitted pair AND surfaced in decision-capture events for audit.
    """

    # ------------------------------------------------------------------
    # Subclass hooks (Wave 113). Keep these as class attributes so
    # subclasses can flip them without overriding ``__init__``.
    # ------------------------------------------------------------------
    _default_base_url: str = DEFAULT_BASE_URL
    _default_model: str = DEFAULT_SYNTHESIS_MODEL
    _default_api_key_env: str = ENV_API_KEY
    _default_model_env: str = ENV_MODEL
    _default_base_url_env: Optional[str] = ENV_BASE_URL
    _api_key_required: bool = True
    _provider_name: str = "together"

    def __init__(
        self,
        *,
        api_key: Optional[str] = None,
        model: Optional[str] = None,
        base_url: Optional[str] = None,
        client: Optional[httpx.Client] = None,
        capture: Optional[Any] = None,
        timeout: float = DEFAULT_TIMEOUT,
        temperature: float = 0.4,
        max_tokens: int = 800,
    ) -> None:
        env_key_name = self._default_api_key_env
        resolved_key = api_key or os.environ.get(env_key_name)
        if (
            client is None
            and not resolved_key
            and self._api_key_required
        ):
            raise RuntimeError(
                f"{env_key_name} required for "
                f"provider={self._provider_name}; "
                "set the env var or inject a client (tests)."
            )
        # Wave 113 prep: when the API key isn't required (local servers
        # that ignore auth), still send *something* in the Authorization
        # header so reverse-proxy servers that DO check auth get a stable
        # placeholder rather than an unset-header surprise.
        if not resolved_key and not self._api_key_required:
            resolved_key = "local"
        self._api_key = resolved_key
        self._model = (
            model
            or os.environ.get(self._default_model_env)
            or self._default_model
        )
        # Wave 113 prep: resolve the base URL with the same precedence
        # the API key + model use — explicit kwarg, then env override
        # (when configured), then class default.
        env_base_url_name = self._default_base_url_env
        env_base_url = (
            os.environ.get(env_base_url_name) if env_base_url_name else None
        )
        self._base_url = (
            base_url or env_base_url or self._default_base_url
        ).rstrip("/")
        self._client = client
        self._capture = capture
        self._timeout = float(timeout)
        self._temperature = float(temperature)
        self._max_tokens = int(max_tokens)

    @property
    def api_url(self) -> str:
        """Full chat-completions endpoint URL for this provider.

        Built from ``self._base_url`` so subclasses (and env overrides)
        flow through automatically. The Together hard-coded constant
        ``TOGETHER_API_URL`` is preserved for back-compat with callers
        that import it directly.
        """
        return f"{self._base_url}/chat/completions"

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def paraphrase_instruction(
        self, draft: Dict[str, Any], chunk: Dict[str, Any]
    ) -> Dict[str, Any]:
        """Paraphrase a draft instruction pair against its chunk."""
        if not isinstance(draft, dict):
            raise TypeError("draft must be a dict")
        chunk_id = str(chunk.get("id") or chunk.get("chunk_id") or "")
        chunk_text = str(chunk.get("text") or "")
        user_prompt = self._render_instruction_user(draft, chunk_id)

        parsed, usage, retry_count = self._call_with_parse(
            system_prompt=_INSTRUCTION_SYSTEM_PROMPT,
            chunk_text=chunk_text,
            user_prompt=user_prompt,
            required_keys=("prompt", "completion"),
        )

        out = dict(draft)
        out["prompt"] = self._clamp(
            parsed["prompt"], kind="prompt", chunk_id=chunk_id
        )
        out["completion"] = self._clamp(
            parsed["completion"], kind="completion", chunk_id=chunk_id
        )
        out["provider"] = self._provider_name

        self._emit_decision(
            kind="instruction",
            draft=draft,
            chunk_id=chunk_id,
            usage=usage,
            retry_count=retry_count,
        )
        return out

    def paraphrase_preference(
        self, draft: Dict[str, Any], chunk: Dict[str, Any]
    ) -> Dict[str, Any]:
        """Paraphrase a draft preference triple against its chunk."""
        if not isinstance(draft, dict):
            raise TypeError("draft must be a dict")
        chunk_id = str(chunk.get("id") or chunk.get("chunk_id") or "")
        chunk_text = str(chunk.get("text") or "")
        user_prompt = self._render_preference_user(draft, chunk_id)

        parsed, usage, retry_count = self._call_with_parse(
            system_prompt=_PREFERENCE_SYSTEM_PROMPT,
            chunk_text=chunk_text,
            user_prompt=user_prompt,
            required_keys=("prompt", "chosen", "rejected"),
        )

        out = dict(draft)
        out["prompt"] = self._clamp(
            parsed["prompt"], kind="prompt", chunk_id=chunk_id
        )
        out["chosen"] = self._clamp(
            parsed["chosen"], kind="chosen", chunk_id=chunk_id
        )
        out["rejected"] = self._clamp(
            parsed["rejected"], kind="rejected", chunk_id=chunk_id
        )
        out["provider"] = self._provider_name

        self._emit_decision(
            kind="preference",
            draft=draft,
            chunk_id=chunk_id,
            usage=usage,
            retry_count=retry_count,
        )
        return out

    # ------------------------------------------------------------------
    # Internals
    # ------------------------------------------------------------------

    @property
    def client(self) -> httpx.Client:
        if self._client is None:
            self._client = httpx.Client(timeout=self._timeout)
        return self._client

    def _build_request(
        self, system_prompt: str, chunk_text: str, user_prompt: str
    ) -> Dict[str, Any]:
        """Build the OpenAI-compatible chat-completions payload.

        Together's chat endpoint takes the standard OpenAI shape; we
        send the (system_prompt, chunk_text) prefix as the system
        message and the rendered draft as the user message.
        """
        full_system = (
            f"{system_prompt}\n\nSource chunk text:\n\n{chunk_text}"
        )
        return {
            "model": self._model,
            "messages": [
                {"role": "system", "content": full_system},
                {"role": "user", "content": user_prompt},
            ],
            "temperature": self._temperature,
            "max_tokens": self._max_tokens,
        }

    def _post_with_retry(
        self, payload: Dict[str, Any]
    ) -> tuple:
        """POST to the chat-completions endpoint with bounded retries.

        Returns ``(parsed_response_dict, retry_count)``. Surfaces
        4xx (other than 429) immediately as
        ``SynthesisProviderError`` with ``code`` set to the HTTP
        status string. Persistent transient failures (5xx / 429)
        after ``MAX_HTTP_RETRIES`` attempts also raise
        ``SynthesisProviderError``.

        URL + log-message provider name are subclass-driven via
        ``self.api_url`` / ``self._provider_name``.
        """
        headers = {
            "Authorization": f"Bearer {self._api_key}" if self._api_key else "",
            "Content-Type": "application/json",
        }
        url = self.api_url
        provider_label = self._provider_name
        last_status: Optional[int] = None
        last_body: str = ""
        for attempt in range(1, MAX_HTTP_RETRIES + 1):
            try:
                response = self.client.post(
                    url,
                    json=payload,
                    headers=headers,
                )
            except httpx.HTTPError as exc:
                last_body = str(exc)
                last_status = None
                if attempt >= MAX_HTTP_RETRIES:
                    raise SynthesisProviderError(
                        f"{provider_label} request to {url} failed after "
                        f"{MAX_HTTP_RETRIES} attempts: {exc}",
                        code="transport_error",
                    ) from exc
                self._sleep_for_attempt(attempt)
                continue

            status = response.status_code
            if status == 200:
                try:
                    body = response.json()
                except ValueError as exc:
                    raise SynthesisProviderError(
                        f"{provider_label} returned non-JSON 200 body: {exc}",
                        code="malformed_response",
                    ) from exc
                return body, attempt - 1

            last_status = status
            try:
                last_body = response.text[:500]
            except Exception:
                last_body = "<unreadable>"

            if status in _RETRYABLE_STATUS and attempt < MAX_HTTP_RETRIES:
                logger.warning(
                    "%s synthesis: transient HTTP %d on attempt "
                    "%d/%d; retrying",
                    provider_label, status, attempt, MAX_HTTP_RETRIES,
                )
                self._sleep_for_attempt(attempt)
                continue

            # Either non-retryable (4xx other than 429) or retries
            # exhausted on a 5xx / 429.
            raise SynthesisProviderError(
                f"{provider_label} returned HTTP {status}: {last_body!r}",
                code=str(status),
            )

        # Defensive: loop exits via return / raise above.
        raise SynthesisProviderError(
            f"{provider_label}: unreachable retry exit (last_status="
            f"{last_status}, last_body={last_body!r})",
            code="retry_exhausted",
        )

    @staticmethod
    def _sleep_for_attempt(attempt: int) -> None:
        """Exponential backoff: 1s, 2s, 4s, ... bounded by attempt."""
        backoff = INITIAL_BACKOFF_SECONDS * (2 ** (attempt - 1))
        time.sleep(backoff)

    def _call_with_parse(
        self,
        *,
        system_prompt: str,
        chunk_text: str,
        user_prompt: str,
        required_keys: tuple,
    ) -> tuple:
        """Issue the HTTP call and parse the JSON response.

        Retries on malformed JSON (model returned text that doesn't
        contain a parseable object with the required keys) up to
        ``MAX_PARSE_RETRIES`` times. Returns
        ``(parsed_keys, usage_dict, http_retry_count)``.
        """
        payload = self._build_request(system_prompt, chunk_text, user_prompt)
        attempts = 0
        last_err: Optional[Exception] = None
        last_text: str = ""
        total_http_retries = 0
        last_usage: Dict[str, int] = {}
        while attempts < MAX_PARSE_RETRIES:
            attempts += 1
            body, http_retries = self._post_with_retry(payload)
            total_http_retries += http_retries
            text = self._extract_text(body)
            last_usage = self._extract_usage(body)
            last_text = text
            try:
                parsed = self._parse_json(text)
            except ValueError as exc:
                last_err = exc
                logger.warning(
                    "%s synthesis: parse retry %d/%d: %s",
                    self._provider_name, attempts, MAX_PARSE_RETRIES, exc,
                )
                continue
            missing = [k for k in required_keys if k not in parsed]
            if missing:
                last_err = ValueError(
                    f"response missing required keys: {missing}"
                )
                continue
            return parsed, last_usage, total_http_retries
        raise SynthesisProviderError(
            f"{type(self).__name__}: failed to parse a valid JSON "
            f"response after {MAX_PARSE_RETRIES} attempts. "
            f"Last error: {last_err}; tail of last response: "
            f"{last_text[-200:]!r}",
            code="parse_retries_exhausted",
        )

    @staticmethod
    def _render_instruction_user(
        draft: Dict[str, Any], chunk_id: str
    ) -> str:
        return (
            f"Chunk ID: {chunk_id}\n"
            f"Bloom level: {draft.get('bloom_level','unknown')}\n"
            f"Content type: {draft.get('content_type','unknown')}\n"
            f"Template ID: {draft.get('template_id','unknown')}\n"
            f"\n"
            f"Draft prompt:\n{draft.get('prompt','')}\n"
            f"\n"
            f"Draft completion:\n{draft.get('completion','')}\n"
            f"\n"
            f"Rewrite the prompt and completion. Return JSON with keys "
            f"'prompt' and 'completion'."
        )

    @staticmethod
    def _render_preference_user(
        draft: Dict[str, Any], chunk_id: str
    ) -> str:
        return (
            f"Chunk ID: {chunk_id}\n"
            f"Source: {draft.get('rejected_source','unknown')}\n"
            f"\n"
            f"Draft prompt:\n{draft.get('prompt','')}\n"
            f"\n"
            f"Draft chosen:\n{draft.get('chosen','')}\n"
            f"\n"
            f"Draft rejected:\n{draft.get('rejected','')}\n"
            f"\n"
            f"Rewrite all three. Return JSON with keys 'prompt', "
            f"'chosen', and 'rejected'."
        )

    @staticmethod
    def _extract_text(body: Dict[str, Any]) -> str:
        """Extract assistant content from an OpenAI-shaped response.

        Together's payload mirrors OpenAI exactly:
        ``{"choices": [{"message": {"content": "..."}}], ...}``.
        """
        choices = body.get("choices") or []
        if not choices:
            return ""
        first = choices[0]
        if not isinstance(first, dict):
            return ""
        message = first.get("message") or {}
        content = message.get("content")
        if isinstance(content, str):
            return content
        return ""

    @staticmethod
    def _extract_usage(body: Dict[str, Any]) -> Dict[str, int]:
        usage = body.get("usage") or {}
        if not isinstance(usage, dict):
            return {}

        def _g(name: str) -> int:
            v = usage.get(name)
            try:
                return int(v) if v is not None else 0
            except (TypeError, ValueError):
                return 0

        return {
            "prompt_tokens": _g("prompt_tokens"),
            "completion_tokens": _g("completion_tokens"),
            "total_tokens": _g("total_tokens"),
        }

    @staticmethod
    def _parse_json(text: str) -> Dict[str, Any]:
        """Tolerant JSON parser. Strips ```json fences; otherwise scans
        for the first balanced JSON object span. Mirrors the Anthropic
        provider's parser shape so downstream behavior is identical."""
        import json as _json
        import re as _re
        if not text or not text.strip():
            raise ValueError("empty response text")
        s = text.strip()
        fence = _re.match(r"^```(?:json)?\s*(.*?)\s*```$", s, _re.DOTALL)
        if fence:
            s = fence.group(1).strip()
        try:
            return _json.loads(s)
        except _json.JSONDecodeError:
            pass
        start = s.find("{")
        if start < 0:
            raise ValueError("no JSON object in response")
        depth = 0
        for i, ch in enumerate(s[start:], start=start):
            if ch == "{":
                depth += 1
            elif ch == "}":
                depth -= 1
                if depth == 0:
                    candidate = s[start:i + 1]
                    return _json.loads(candidate)
        raise ValueError("unbalanced JSON object in response")

    @staticmethod
    def _clamp(text: str, kind: str, *, chunk_id: Optional[str] = None) -> str:
        """Clamp paraphrased text to the [lo, hi] bounds for ``kind``.

        Wave 112 invariant — short responses raise
        ``SynthesisProviderError`` (no sentinel-filler injection); over-
        max strings are truncated on a sentence boundary when possible.
        Bounds are shared with the Anthropic provider via
        ``_KIND_BOUNDS``.
        """
        try:
            lo, hi = _KIND_BOUNDS[kind]
        except KeyError as exc:
            raise ValueError(
                f"_clamp: unknown kind={kind!r}; expected one of "
                f"{sorted(_KIND_BOUNDS)}"
            ) from exc
        s = (text or "").strip()
        if len(s) < lo:
            raise SynthesisProviderError(
                f"{kind} length {len(s)} below minimum {lo}; refusing to "
                f"inject sentinel filler. Caller should retry the paraphrase.",
                code=f"{kind}_below_minimum",
                chunk_id=chunk_id,
            )
        if len(s) > hi:
            hard = s[:hi]
            period = hard.rfind(". ")
            if period > lo:
                s = hard[: period + 1]
            else:
                s = hard.rstrip() + "..."
        return s

    def _emit_decision(
        self,
        *,
        kind: str,
        draft: Dict[str, Any],
        chunk_id: str,
        usage: Dict[str, int],
        retry_count: int,
    ) -> None:
        if self._capture is None:
            return
        prompt_tokens = int(usage.get("prompt_tokens", 0))
        completion_tokens = int(usage.get("completion_tokens", 0))
        try:
            self._capture.log_decision(
                decision_type="synthesis_provider_call",
                decision=self._build_decision_string(
                    kind=kind,
                    chunk_id=chunk_id,
                    prompt_tokens=prompt_tokens,
                    completion_tokens=completion_tokens,
                    retry_count=retry_count,
                ),
                rationale=self._build_decision_rationale(
                    kind=kind,
                    draft=draft,
                    chunk_id=chunk_id,
                    prompt_tokens=prompt_tokens,
                    completion_tokens=completion_tokens,
                    retry_count=retry_count,
                ),
            )
        except Exception as exc:  # pragma: no cover — defensive
            logger.warning("synthesis_provider_call capture failed: %s", exc)

    # ------------------------------------------------------------------
    # Decision-capture string builders (Wave 113 prep — subclass hooks).
    # Subclasses override to interpolate provider-specific signals
    # (e.g. base_url for the local provider) without copy-pasting the
    # _emit_decision wiring above.
    # ------------------------------------------------------------------

    def _build_decision_string(
        self,
        *,
        kind: str,
        chunk_id: str,
        prompt_tokens: int,
        completion_tokens: int,
        retry_count: int,
    ) -> str:
        return (
            f"Together paraphrase ({kind}) for chunk {chunk_id} "
            f"using model {self._model}; "
            f"prompt_tokens={prompt_tokens}, "
            f"completion_tokens={completion_tokens}, "
            f"retry_count={retry_count}."
        )

    def _build_decision_rationale(
        self,
        *,
        kind: str,
        draft: Dict[str, Any],
        chunk_id: str,
        prompt_tokens: int,
        completion_tokens: int,
        retry_count: int,
    ) -> str:
        return (
            f"Routing template-generated {kind} draft "
            f"(template_id={draft.get('template_id','n/a')}, "
            f"draft_prompt_len={len(str(draft.get('prompt','')))}, "
            f"chunk_id={chunk_id}) through Together AI's hosted "
            f"OSS model {self._model} for paraphrase. Together's "
            f"ToS permits using this output as training data for "
            f"another model, which Anthropic's ToS forbids — this "
            f"is the ToS-clean teacher pass for the SLM corpus. "
            f"prompt_tokens={prompt_tokens}, "
            f"completion_tokens={completion_tokens}, "
            f"http_retries={retry_count}."
        )


__all__ = [
    "TogetherSynthesisProvider",
    "DEFAULT_SYNTHESIS_MODEL",
    "DEFAULT_BASE_URL",
    "TOGETHER_API_URL",
    "ENV_API_KEY",
    "ENV_MODEL",
    "ENV_BASE_URL",
    "MAX_HTTP_RETRIES",
    "MAX_PARSE_RETRIES",
    "DEFAULT_TIMEOUT",
    "INITIAL_BACKOFF_SECONDS",
    "_RETRYABLE_STATUS",
    "SynthesisProviderError",
]
