#!/usr/bin/env python3
"""Together AI synthesis provider — composes :class:`OpenAICompatibleClient`.

Wraps the deterministic mock-provider drafts produced by
:mod:`Trainforge.generators.instruction_factory` and
:mod:`Trainforge.generators.preference_factory` in an OSS-teacher
paraphrase + verify pass. Routes through Together AI's OpenAI-compatible
chat-completions endpoint, which (unlike Anthropic's ToS) explicitly
permits using the model output as training data for another model. This
is the ToS-clean teacher pass for SLM training-data generation.

Default model: ``meta-llama/Llama-3.3-70B-Instruct-Turbo``. Override via
``TOGETHER_SYNTHESIS_MODEL`` (e.g. ``Qwen/Qwen2.5-72B-Instruct-Turbo``,
``deepseek-ai/DeepSeek-V3``).

Architecture (LLM-agnostic refactor): the OpenAI ``/v1/chat/completions``
HTTP machinery — retries, timeouts, JSON parse, error mapping, decision-
capture rationale construction — lives once in
:class:`Trainforge.generators._openai_compatible_client.OpenAICompatibleClient`.
This provider composes one such client and concentrates on the
task-specific surface: instruction / preference paraphrase prompts,
length clamping, JSON parsing of the rendered draft envelope.

Mirrors :class:`AnthropicSynthesisProvider`:

- Same public surface: ``paraphrase_instruction`` / ``paraphrase_preference``.
- Same length-clamp invariant (Wave 112): short paraphrases raise
  ``SynthesisProviderError`` rather than getting padded with sentinel
  filler; over-max strings get truncated on a sentence boundary.
- Same ``synthesis_provider_call`` decision-capture event per call,
  with a rationale that interpolates the chunk_id, model, retry count,
  and token counts (≥20 chars per the project's LLM call-site
  instrumentation contract).
- Output ``provider`` field is ``"together"``.

Differences from the Anthropic provider:

- HTTP-driven (``httpx`` + bearer auth); no SDK install required.
- Retry policy: transient HTTP failures (429 / 503) are retried with
  exponential backoff up to ``MAX_HTTP_RETRIES`` attempts. Other 4xx
  surface immediately as ``SynthesisProviderError(code=str(status))``.
- No prompt-caching API on Together — chunk text is sent on every
  request, accepted as a per-call cost.
"""

from __future__ import annotations

import json as _json
import logging
import os
import re as _re
import time
from typing import Any, Dict, List, Optional, Tuple

import httpx

from Trainforge.generators._anthropic_provider import (  # noqa: F401
    COMPLETION_MAX,
    COMPLETION_MIN,
    PROMPT_MAX,
    PROMPT_MIN,
    SynthesisProviderError,
    _KIND_BOUNDS,
)
from Trainforge.generators._openai_compatible_client import (
    OpenAICompatibleClient,
)

logger = logging.getLogger(__name__)


DEFAULT_SYNTHESIS_MODEL = "meta-llama/Llama-3.3-70B-Instruct-Turbo"
DEFAULT_BASE_URL = "https://api.together.xyz/v1"
# Backwards-compat alias for callers that imported the full URL constant
# directly. Kept identical to the legacy hard-coded value so existing tests
# keep matching against ``str(req.url) == TOGETHER_API_URL``.
TOGETHER_API_URL = "https://api.together.xyz/v1/chat/completions"
ENV_API_KEY = "TOGETHER_API_KEY"
ENV_MODEL = "TOGETHER_SYNTHESIS_MODEL"
# Wave 113: the Together provider doesn't accept a base-URL env override.
# Kept None so subclasses that DO want one (e.g. ``LocalSynthesisProvider``
# whose server URL varies per Ollama / vLLM / llama.cpp / LM Studio install)
# can flip it to a real env-var name without touching the base class.
ENV_BASE_URL: Optional[str] = None

# Hard cap on retry attempts when the endpoint returns a transient error.
# Surfaced through to the embedded ``OpenAICompatibleClient``.
MAX_HTTP_RETRIES = 3
# Hard cap on retry attempts when the model returns malformed JSON.
MAX_PARSE_RETRIES = 10
# Default per-call HTTP timeout (seconds).
DEFAULT_TIMEOUT = 60.0
# Initial backoff in seconds; doubled per retry.
INITIAL_BACKOFF_SECONDS = 1.0
# Status codes we treat as transient and retry. Mirrored on the embedded
# client's ``retry_status_codes``.
_RETRYABLE_STATUS = frozenset({429, 500, 502, 503, 504})


# ---------------------------------------------------------------------------
# System prompt fragments — reused from the Anthropic provider's contract
# so paraphrased output stays interchangeable across providers.
# ---------------------------------------------------------------------------

_INSTRUCTION_SYSTEM_PROMPT = (
    "You are a paraphrase-and-verify assistant for instruction-tuning data. "
    "You receive a draft (prompt, completion) pair generated by a deterministic "
    "template, plus the chunk text the pair was grounded in. Your job is to "
    "rewrite the prompt and completion so they read naturally and vary lexically, "
    "WITHOUT introducing any fact, claim, term, or example that does not appear "
    "in the chunk text. If the draft is already faithful, paraphrase it; never "
    "fabricate. Preserve the cognitive level (Bloom's) of the original. Return "
    "ONLY a single valid JSON object with keys 'prompt' and 'completion' — no "
    "preamble, no markdown fences, no commentary."
)

_PREFERENCE_SYSTEM_PROMPT = (
    "You are a paraphrase-and-verify assistant for preference-tuning data (DPO). "
    "You receive a draft (prompt, chosen, rejected) triple plus the chunk text. "
    "Rewrite all three so they read naturally and vary lexically, WITHOUT "
    "introducing any fact not in the chunk. The 'chosen' completion must remain "
    "factually correct; the 'rejected' completion must remain plausibly wrong "
    "(a misconception or weak answer) so the preference signal is preserved. "
    "Return ONLY a single valid JSON object with keys 'prompt', 'chosen', and "
    "'rejected' — no preamble, no markdown fences, no commentary."
)


# ---------------------------------------------------------------------------
# Provider class
# ---------------------------------------------------------------------------


class TogetherSynthesisProvider:
    """Paraphrases mock-provider drafts via Together AI's hosted OSS models.

    Constructor resolves the API key from the ``TOGETHER_API_KEY``
    environment variable when ``api_key`` isn't passed. Model defaults to
    ``meta-llama/Llama-3.3-70B-Instruct-Turbo`` and is overridable via
    the ``TOGETHER_SYNTHESIS_MODEL`` env var or the ``model`` kwarg.

    The HTTP client is owned by the provider and can be supplied via the
    ``client`` kwarg (tests inject one with ``httpx.MockTransport``).

    Composition: the constructor builds an
    :class:`OpenAICompatibleClient` with ``provider_label="together"``
    and stores it as ``self._oa_client``. The paraphrase methods delegate
    to ``self._oa_client.chat_completion(...)`` for the HTTP call and
    only own the prompt construction + length clamping + parse-retry.

    Subclass hooks (Wave 113 prep — used by
    :class:`Trainforge.generators._local_provider.LocalSynthesisProvider`):

    - ``_default_base_url``: provider-specific OpenAI-compatible base URL
      (the ``/chat/completions`` suffix is appended at request time).
    - ``_default_model``: short / repo-style model identifier.
    - ``_default_api_key_env`` / ``_default_model_env`` /
      ``_default_base_url_env``: env var names the constructor reads to
      populate the resolved value when no explicit kwarg is supplied.
      ``None`` for ``_default_base_url_env`` (the Together case) means
      the base URL isn't env-overridable on this provider.
    - ``_api_key_required``: when ``False``, the constructor accepts
      callers that didn't set the API-key env var and didn't inject a
      client — needed for local model servers that ignore auth.
    - ``_provider_name``: string written to ``out["provider"]`` on every
      emitted pair AND surfaced in decision-capture events for audit.
      Also flowed through to the embedded client's ``provider_label``
      so the Wave-115 ``llm_chat_call`` audit row identifies the
      backend.
    """

    # ------------------------------------------------------------------
    # Subclass hooks (Wave 113). Keep these as class attributes so
    # subclasses can flip them without overriding ``__init__``.
    # ------------------------------------------------------------------
    _default_base_url: str = DEFAULT_BASE_URL
    _default_model: str = DEFAULT_SYNTHESIS_MODEL
    _default_api_key_env: str = ENV_API_KEY
    _default_model_env: str = ENV_MODEL
    _default_base_url_env: Optional[str] = ENV_BASE_URL
    _api_key_required: bool = True
    _provider_name: str = "together"

    def __init__(
        self,
        *,
        api_key: Optional[str] = None,
        model: Optional[str] = None,
        base_url: Optional[str] = None,
        client: Optional[httpx.Client] = None,
        capture: Optional[Any] = None,
        timeout: float = DEFAULT_TIMEOUT,
        temperature: float = 0.4,
        max_tokens: int = 800,
    ) -> None:
        env_key_name = self._default_api_key_env
        resolved_key = api_key or os.environ.get(env_key_name)
        if (
            client is None
            and not resolved_key
            and self._api_key_required
        ):
            raise RuntimeError(
                f"{env_key_name} required for "
                f"provider={self._provider_name}; "
                "set the env var or inject a client (tests)."
            )
        # Wave 113 prep: when the API key isn't required (local servers
        # that ignore auth), still send *something* in the Authorization
        # header so reverse-proxy servers that DO check auth get a stable
        # placeholder rather than an unset-header surprise.
        if not resolved_key and not self._api_key_required:
            resolved_key = "local"
        self._api_key = resolved_key
        self._model = (
            model
            or os.environ.get(self._default_model_env)
            or self._default_model
        )
        # Wave 113 prep: resolve the base URL with the same precedence
        # the API key + model use — explicit kwarg, then env override
        # (when configured), then class default.
        env_base_url_name = self._default_base_url_env
        env_base_url = (
            os.environ.get(env_base_url_name) if env_base_url_name else None
        )
        self._base_url = (
            base_url or env_base_url or self._default_base_url
        ).rstrip("/")
        self._client = client
        self._capture = capture
        self._timeout = float(timeout)
        self._temperature = float(temperature)
        self._max_tokens = int(max_tokens)

        # Composition: build the LLM-agnostic client. The client owns the
        # HTTP retry loop, JSON parse of the response envelope, and
        # ``llm_chat_call`` decision-capture emit. This provider keeps
        # ``synthesis_provider_call`` capture as the higher-level audit
        # event (one per paraphrase call); the lower-level
        # ``llm_chat_call`` event is intentionally not wired to keep the
        # legacy decision-capture surface stable. Only one event per
        # paraphrase call lands in the capture stream.
        #
        # Wave 113: ``json_mode=True`` defense-in-depth — Together's
        # hosted Llama-3.3-70B and Qwen2.5-72B are more reliable at
        # JSON than 7B local models, but the cost of sending both
        # ``format`` and ``response_format`` is zero (the server ignores
        # whichever it doesn't recognize) and gives us consistent JSON
        # output across hosted-OSS providers (Fireworks, Groq, DeepInfra
        # all accept ``response_format``).
        self._oa_client = OpenAICompatibleClient(
            base_url=self._base_url,
            model=self._model,
            api_key=self._api_key,
            capture=None,
            timeout=self._timeout,
            max_retries=MAX_HTTP_RETRIES,
            retry_status_codes=tuple(sorted(_RETRYABLE_STATUS)),
            initial_backoff_seconds=INITIAL_BACKOFF_SECONDS,
            provider_label=self._provider_name,
            client=client,
            # Route the retry-backoff sleep through this module's
            # ``time`` so existing tests that patch
            # ``Trainforge.generators._together_provider.time.sleep``
            # (and the equivalent local-provider patch) keep working
            # after the refactor.
            sleep_fn=lambda s: time.sleep(s),
            json_mode=True,
        )

    @property
    def api_url(self) -> str:
        """Full chat-completions endpoint URL for this provider.

        Built from ``self._base_url`` so subclasses (and env overrides)
        flow through automatically. The Together hard-coded constant
        ``TOGETHER_API_URL`` is preserved for back-compat with callers
        that import it directly.
        """
        return f"{self._base_url}/chat/completions"

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def paraphrase_instruction(
        self, draft: Dict[str, Any], chunk: Dict[str, Any]
    ) -> Dict[str, Any]:
        """Paraphrase a draft instruction pair against its chunk."""
        if not isinstance(draft, dict):
            raise TypeError("draft must be a dict")
        chunk_id = str(chunk.get("id") or chunk.get("chunk_id") or "")
        chunk_text = str(chunk.get("text") or "")
        user_prompt = self._render_instruction_user(draft, chunk_id)

        parsed, usage, retry_count = self._call_with_parse(
            system_prompt=_INSTRUCTION_SYSTEM_PROMPT,
            chunk_text=chunk_text,
            user_prompt=user_prompt,
            required_keys=("prompt", "completion"),
        )

        out = dict(draft)
        out["prompt"] = self._clamp(
            parsed["prompt"], kind="prompt", chunk_id=chunk_id
        )
        out["completion"] = self._clamp(
            parsed["completion"], kind="completion", chunk_id=chunk_id
        )
        out["provider"] = self._provider_name

        self._emit_decision(
            kind="instruction",
            draft=draft,
            chunk_id=chunk_id,
            usage=usage,
            retry_count=retry_count,
        )
        return out

    def paraphrase_preference(
        self, draft: Dict[str, Any], chunk: Dict[str, Any]
    ) -> Dict[str, Any]:
        """Paraphrase a draft preference triple against its chunk."""
        if not isinstance(draft, dict):
            raise TypeError("draft must be a dict")
        chunk_id = str(chunk.get("id") or chunk.get("chunk_id") or "")
        chunk_text = str(chunk.get("text") or "")
        user_prompt = self._render_preference_user(draft, chunk_id)

        parsed, usage, retry_count = self._call_with_parse(
            system_prompt=_PREFERENCE_SYSTEM_PROMPT,
            chunk_text=chunk_text,
            user_prompt=user_prompt,
            required_keys=("prompt", "chosen", "rejected"),
        )

        out = dict(draft)
        out["prompt"] = self._clamp(
            parsed["prompt"], kind="prompt", chunk_id=chunk_id
        )
        out["chosen"] = self._clamp(
            parsed["chosen"], kind="chosen", chunk_id=chunk_id
        )
        out["rejected"] = self._clamp(
            parsed["rejected"], kind="rejected", chunk_id=chunk_id
        )
        out["provider"] = self._provider_name

        self._emit_decision(
            kind="preference",
            draft=draft,
            chunk_id=chunk_id,
            usage=usage,
            retry_count=retry_count,
        )
        return out

    # ------------------------------------------------------------------
    # Internals
    # ------------------------------------------------------------------

    @property
    def client(self) -> httpx.Client:
        """Backwards-compat: return the underlying httpx client.

        The embedded ``OpenAICompatibleClient`` owns the actual transport
        now; this property surfaces it so existing tests that assert
        ``provider.client is injected_client`` continue to work.
        """
        return self._oa_client.client

    def _build_messages(
        self, system_prompt: str, chunk_text: str, user_prompt: str
    ) -> List[Dict[str, str]]:
        """Build the OpenAI-compatible messages array.

        The (system_prompt + chunk_text) prefix becomes a single system
        message; the rendered draft is the user message. The shape +
        content remain identical to the pre-refactor request.
        """
        full_system = (
            f"{system_prompt}\n\nSource chunk text:\n\n{chunk_text}"
        )
        return [
            {"role": "system", "content": full_system},
            {"role": "user", "content": user_prompt},
        ]

    def _call_with_parse(
        self,
        *,
        system_prompt: str,
        chunk_text: str,
        user_prompt: str,
        required_keys: tuple,
    ) -> Tuple[Dict[str, Any], Dict[str, int], int]:
        """Issue the HTTP call (via the embedded client) and parse JSON.

        Retries on malformed JSON (model returned text without a parseable
        object carrying the required keys) up to ``MAX_PARSE_RETRIES``
        times. Returns ``(parsed_keys, usage_dict, http_retry_count)``.
        ``usage_dict`` is the OpenAI-shape token tally extracted from the
        last successful HTTP response.
        """
        messages = self._build_messages(system_prompt, chunk_text, user_prompt)
        attempts = 0
        last_err: Optional[Exception] = None
        last_text: str = ""
        total_http_retries = 0
        last_usage: Dict[str, int] = {}
        while attempts < MAX_PARSE_RETRIES:
            attempts += 1
            text, usage, http_retries = self._chat_completion_raw(messages)
            total_http_retries += http_retries
            last_usage = usage
            last_text = text
            try:
                parsed = self._parse_json(text)
            except ValueError as exc:
                last_err = exc
                logger.warning(
                    "%s synthesis: parse retry %d/%d: %s",
                    self._provider_name, attempts, MAX_PARSE_RETRIES, exc,
                )
                continue
            missing = [k for k in required_keys if k not in parsed]
            if missing:
                last_err = ValueError(
                    f"response missing required keys: {missing}"
                )
                continue
            return parsed, last_usage, total_http_retries
        raise SynthesisProviderError(
            f"{type(self).__name__}: failed to parse a valid JSON "
            f"response after {MAX_PARSE_RETRIES} attempts. "
            f"Last error: {last_err}; tail of last response: "
            f"{last_text[-200:]!r}",
            code="parse_retries_exhausted",
        )

    def _chat_completion_raw(
        self, messages: List[Dict[str, str]]
    ) -> Tuple[str, Dict[str, int], int]:
        """Run one chat call via the embedded client and return raw shape.

        Returns ``(assistant_text, usage_dict, retry_count)``. Splitting
        this out from ``_call_with_parse`` keeps the parse-retry loop
        legible. Each attempt issues exactly one HTTP call (modulo the
        client's own transient-status retries).
        """
        # Direct-route helper used to expose ``_post_with_retry`` results
        # so this provider's parse-retry loop can layer cleanly on top.
        # The client's ``chat_completion`` is the public entry point;
        # this helper mirrors it but exposes the retry count instead of
        # collapsing it into the decision rationale.
        payload: Dict[str, Any] = {
            "model": self._model,
            "messages": messages,
            "temperature": self._temperature,
            "max_tokens": self._max_tokens,
        }
        body, retry_count = self._oa_client._post_with_retry(payload)
        text = self._oa_client._extract_text(body)
        usage = self._oa_client._extract_usage(body)
        return text, usage, retry_count

    # ------------------------------------------------------------------
    # Strict-JSON directives appended to the user prompt (Wave 113).
    # Defense in depth: while Together's 70B-class hosted models are
    # reliable at JSON output via ``response_format``, an explicit
    # end-of-prompt directive eliminates the rare drift that still
    # surfaces on Llama-3.3 / Qwen2.5 when the hosted server ignores
    # ``response_format`` (some hosted-OSS servers do).
    # ------------------------------------------------------------------
    _INSTRUCTION_JSON_DIRECTIVE = (
        "\n\nRESPOND ONLY WITH A JSON OBJECT. Use EXACTLY this shape, "
        "nothing else:\n"
        "{\"prompt\": \"<paraphrased prompt>\", "
        "\"completion\": \"<paraphrased completion>\"}\n"
        "Do not wrap in markdown. Do not add commentary. Output the "
        "JSON object only."
    )

    _PREFERENCE_JSON_DIRECTIVE = (
        "\n\nRESPOND ONLY WITH A JSON OBJECT. Use EXACTLY this shape, "
        "nothing else:\n"
        "{\"prompt\": \"<paraphrased prompt>\", "
        "\"chosen\": \"<paraphrased chosen>\", "
        "\"rejected\": \"<paraphrased rejected>\"}\n"
        "Do not wrap in markdown. Do not add commentary. Output the "
        "JSON object only."
    )

    @classmethod
    def _render_instruction_user(
        cls, draft: Dict[str, Any], chunk_id: str
    ) -> str:
        return (
            f"Chunk ID: {chunk_id}\n"
            f"Bloom level: {draft.get('bloom_level','unknown')}\n"
            f"Content type: {draft.get('content_type','unknown')}\n"
            f"Template ID: {draft.get('template_id','unknown')}\n"
            f"\n"
            f"Draft prompt:\n{draft.get('prompt','')}\n"
            f"\n"
            f"Draft completion:\n{draft.get('completion','')}\n"
            f"\n"
            f"Rewrite the prompt and completion. Return JSON with keys "
            f"'prompt' and 'completion'."
            f"{cls._INSTRUCTION_JSON_DIRECTIVE}"
        )

    @classmethod
    def _render_preference_user(
        cls, draft: Dict[str, Any], chunk_id: str
    ) -> str:
        return (
            f"Chunk ID: {chunk_id}\n"
            f"Source: {draft.get('rejected_source','unknown')}\n"
            f"\n"
            f"Draft prompt:\n{draft.get('prompt','')}\n"
            f"\n"
            f"Draft chosen:\n{draft.get('chosen','')}\n"
            f"\n"
            f"Draft rejected:\n{draft.get('rejected','')}\n"
            f"\n"
            f"Rewrite all three. Return JSON with keys 'prompt', "
            f"'chosen', and 'rejected'."
            f"{cls._PREFERENCE_JSON_DIRECTIVE}"
        )

    @staticmethod
    def _parse_json(text: str) -> Dict[str, Any]:
        """Tolerant JSON parser.

        Strips ```json fences; otherwise scans for the first balanced
        JSON object span. Mirrors the Anthropic provider's parser shape
        so downstream behavior is identical.
        """
        if not text or not text.strip():
            raise ValueError("empty response text")
        s = text.strip()
        fence = _re.match(r"^```(?:json)?\s*(.*?)\s*```$", s, _re.DOTALL)
        if fence:
            s = fence.group(1).strip()
        try:
            return _json.loads(s)
        except _json.JSONDecodeError:
            pass
        start = s.find("{")
        if start < 0:
            raise ValueError("no JSON object in response")
        depth = 0
        for i, ch in enumerate(s[start:], start=start):
            if ch == "{":
                depth += 1
            elif ch == "}":
                depth -= 1
                if depth == 0:
                    candidate = s[start:i + 1]
                    return _json.loads(candidate)
        raise ValueError("unbalanced JSON object in response")

    @staticmethod
    def _clamp(text: str, kind: str, *, chunk_id: Optional[str] = None) -> str:
        """Clamp paraphrased text to the [lo, hi] bounds for ``kind``.

        Wave 112 invariant — short responses raise
        ``SynthesisProviderError`` (no sentinel-filler injection); over-
        max strings are truncated on a sentence boundary when possible.
        Bounds are shared with the Anthropic provider via
        ``_KIND_BOUNDS``.
        """
        try:
            lo, hi = _KIND_BOUNDS[kind]
        except KeyError as exc:
            raise ValueError(
                f"_clamp: unknown kind={kind!r}; expected one of "
                f"{sorted(_KIND_BOUNDS)}"
            ) from exc
        s = (text or "").strip()
        if len(s) < lo:
            raise SynthesisProviderError(
                f"{kind} length {len(s)} below minimum {lo}; refusing to "
                f"inject sentinel filler. Caller should retry the paraphrase.",
                code=f"{kind}_below_minimum",
                chunk_id=chunk_id,
            )
        if len(s) > hi:
            hard = s[:hi]
            period = hard.rfind(". ")
            if period > lo:
                s = hard[: period + 1]
            else:
                s = hard.rstrip() + "..."
        return s

    def _emit_decision(
        self,
        *,
        kind: str,
        draft: Dict[str, Any],
        chunk_id: str,
        usage: Dict[str, int],
        retry_count: int,
    ) -> None:
        if self._capture is None:
            return
        prompt_tokens = int(usage.get("prompt_tokens", 0))
        completion_tokens = int(usage.get("completion_tokens", 0))
        try:
            self._capture.log_decision(
                decision_type="synthesis_provider_call",
                decision=self._build_decision_string(
                    kind=kind,
                    chunk_id=chunk_id,
                    prompt_tokens=prompt_tokens,
                    completion_tokens=completion_tokens,
                    retry_count=retry_count,
                ),
                rationale=self._build_decision_rationale(
                    kind=kind,
                    draft=draft,
                    chunk_id=chunk_id,
                    prompt_tokens=prompt_tokens,
                    completion_tokens=completion_tokens,
                    retry_count=retry_count,
                ),
            )
        except Exception as exc:  # pragma: no cover — defensive
            logger.warning("synthesis_provider_call capture failed: %s", exc)

    # ------------------------------------------------------------------
    # Decision-capture string builders (Wave 113 — subclass hooks).
    # Subclasses override to interpolate provider-specific signals
    # (e.g. base_url for the local provider) without copy-pasting the
    # _emit_decision wiring above.
    # ------------------------------------------------------------------

    def _build_decision_string(
        self,
        *,
        kind: str,
        chunk_id: str,
        prompt_tokens: int,
        completion_tokens: int,
        retry_count: int,
    ) -> str:
        return (
            f"Together paraphrase ({kind}) for chunk {chunk_id} "
            f"using model {self._model}; "
            f"prompt_tokens={prompt_tokens}, "
            f"completion_tokens={completion_tokens}, "
            f"retry_count={retry_count}."
        )

    def _build_decision_rationale(
        self,
        *,
        kind: str,
        draft: Dict[str, Any],
        chunk_id: str,
        prompt_tokens: int,
        completion_tokens: int,
        retry_count: int,
    ) -> str:
        return (
            f"Routing template-generated {kind} draft "
            f"(template_id={draft.get('template_id','n/a')}, "
            f"draft_prompt_len={len(str(draft.get('prompt','')))}, "
            f"chunk_id={chunk_id}) through Together AI's hosted "
            f"OSS model {self._model} for paraphrase. Together's "
            f"ToS permits using this output as training data for "
            f"another model, which Anthropic's ToS forbids — this "
            f"is the ToS-clean teacher pass for the SLM corpus. "
            f"prompt_tokens={prompt_tokens}, "
            f"completion_tokens={completion_tokens}, "
            f"http_retries={retry_count}."
        )


__all__ = [
    "TogetherSynthesisProvider",
    "DEFAULT_SYNTHESIS_MODEL",
    "DEFAULT_BASE_URL",
    "TOGETHER_API_URL",
    "ENV_API_KEY",
    "ENV_MODEL",
    "ENV_BASE_URL",
    "MAX_HTTP_RETRIES",
    "MAX_PARSE_RETRIES",
    "DEFAULT_TIMEOUT",
    "INITIAL_BACKOFF_SECONDS",
    "_RETRYABLE_STATUS",
    "SynthesisProviderError",
]
