"""Anti-drift contract: the closed Touch.provider enum stays in sync.

The closed ``Touch.provider`` provenance set is DERIVED from the unified
endpoint registry (``config/endpoints.yaml``) via
``lib.llm.endpoints.provenance_provider_names()``. Three sites must agree
with that single authority:

1. Runtime: ``Courseforge/scripts/blocks.py::_TOUCH_PROVIDERS``.
2. Static: ``schemas/knowledge/courseforge_jsonld_v1.schema.json``
   ``$defs.Touch.properties.provider.enum``.
3. Static: ``schemas/context/courseforge_v1.shacl.ttl`` ``ed4all:provider``
   ``sh:in`` list (+ the ``sh:message`` count word).

The two static sites are GENERATED by
``scripts/codegen/sync_provenance_enum.py``; this test fails the build if
any site disagrees with the derived set, replacing the old implicit
"three files stay in sync by hand" with a machine-enforced invariant.
"""

from __future__ import annotations

import json
import re
import subprocess
import sys
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[2]
JSONLD_SCHEMA = REPO_ROOT / "schemas" / "knowledge" / "courseforge_jsonld_v1.schema.json"
SHACL_TTL = REPO_ROOT / "schemas" / "context" / "courseforge_v1.shacl.ttl"
BLOCK_ROUTING_SCHEMA = (
    REPO_ROOT / "schemas" / "courseforge" / "block_routing.schema.json"
)


@pytest.fixture(scope="module")
def derived_set():
    from lib.llm.endpoints import provenance_provider_names

    return set(provenance_provider_names())


@pytest.fixture(scope="module")
def derived_routing_set():
    """The block_routing Spec.provider enum: routable endpoint names + alias.

    DISTINCT from ``derived_set`` (the collapsed PROVENANCE union): every
    endpoint is routable per (block_type, tier), so this set is the
    un-collapsed endpoint-name set (groq/fireworks/deepseek/together-vision
    all appear) plus the legacy ``openai_compatible`` alias.
    """
    from lib.llm.endpoints import endpoint_names

    return set(endpoint_names()) | {"openai_compatible"}


def test_blocks_runtime_frozenset_matches_registry(derived_set):
    from Courseforge.scripts import blocks

    assert set(blocks._TOUCH_PROVIDERS) == derived_set


def test_jsonld_schema_enum_matches_registry(derived_set):
    doc = json.loads(JSONLD_SCHEMA.read_text(encoding="utf-8"))
    enum = doc["$defs"]["Touch"]["properties"]["provider"]["enum"]
    assert set(enum) == derived_set
    # No dupes.
    assert len(enum) == len(set(enum))


def test_shacl_sh_in_matches_registry(derived_set):
    text = SHACL_TTL.read_text(encoding="utf-8")
    # Grab the provider sh:in list: the one immediately before the
    # provider sh:message. Scope by anchoring on the provider message.
    msg = re.search(
        r'sh:message "Touch\.provider is required and must be one of the '
        r'(?P<count>\d+) canonical providers\."',
        text,
    )
    assert msg, "provider sh:message not found in SHACL shapes"
    in_lists = list(re.finditer(r"sh:in \(([^)]*)\)", text[: msg.start()]))
    assert in_lists, "provider sh:in list not found"
    tokens = re.findall(r'"([^"]+)"', in_lists[-1].group(1))
    assert set(tokens) == derived_set
    # The count word in sh:message equals len().
    assert int(msg.group("count")) == len(derived_set)


def test_block_routing_schema_enum_matches_registry(derived_routing_set):
    """block_routing Spec.provider enum == routable endpoint names + alias.

    Fixes the historical schema/code drift where the block_routing enum
    omitted ``claude_session`` (and ``nvidia``): the enum is now GENERATED
    from the endpoint registry by ``sync_provenance_enum.py``.
    """
    doc = json.loads(BLOCK_ROUTING_SCHEMA.read_text(encoding="utf-8"))
    enum = doc["$defs"]["Spec"]["properties"]["provider"]["enum"]
    assert set(enum) == derived_routing_set
    # No dupes.
    assert len(enum) == len(set(enum))
    # The fixed-drift values are present.
    assert "claude_session" in enum
    assert "nvidia" in enum


def test_block_routing_schema_enum_matches_router_allowlist():
    """The schema enum and the runtime router allowlist are the same set."""
    from Courseforge.router.router import _ALLOWED_PROVIDERS

    doc = json.loads(BLOCK_ROUTING_SCHEMA.read_text(encoding="utf-8"))
    enum = doc["$defs"]["Spec"]["properties"]["provider"]["enum"]
    assert set(enum) == set(_ALLOWED_PROVIDERS)


def test_codegen_check_exits_clean():
    """`sync_provenance_enum --check` must pass on the committed files."""
    proc = subprocess.run(
        [sys.executable, "-m", "scripts.codegen.sync_provenance_enum", "--check"],
        cwd=str(REPO_ROOT),
        capture_output=True,
        text=True,
    )
    assert proc.returncode == 0, (
        f"sync_provenance_enum --check reported drift:\n"
        f"stdout={proc.stdout}\nstderr={proc.stderr}"
    )
