"""Wave 76: tests for ``scripts/wave76_clean_concept_graph.py``.

Validates the retroactive cleanup script:

1. Drops nodes whose Wave 76 class is in ``DROPPABLE_CLASSES``.
2. Keeps DomainConcept (and Misconception, by extension).
3. Removes edges whose endpoint(s) refer to dropped nodes.
4. Backs up the original graph before in-place rewrite (``.wave76.bak``).
5. Reports counts before/after, broken down by class.
6. Produces a report whose ``nodes_after`` count equals the kept-class
   total summed.

The script is exercised on a STUB concept graph so the test doesn't
depend on the rdf-shacl-550 archive (which lives under
``LibV2/courses/`` and is regenerated by other Wave 76 workers).
"""

from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any, Dict

import pytest

# Make the scripts package importable as a module path. The script
# itself sits at ``scripts/wave76_clean_concept_graph.py`` and works
# fine as a top-level import once ``scripts/`` is on sys.path.
PROJECT_ROOT = Path(__file__).resolve().parents[2]
SCRIPTS_DIR = PROJECT_ROOT / "scripts"
for path in (str(PROJECT_ROOT), str(SCRIPTS_DIR)):
    if path not in sys.path:
        sys.path.insert(0, path)

import wave76_clean_concept_graph as cleaner  # noqa: E402


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _stub_graph() -> Dict[str, Any]:
    """Build a minimal concept graph mixing clean + noisy nodes.

    Mix layout (chosen so every Wave 76 droppable class appears):
    - DomainConcept survivors: ``rdf-graph``, ``blank-node``,
      ``sparql-select``, ``turtle``.
    - PedagogicalMarker drops: ``key-takeaway``, ``rubric``.
    - AssessmentOption drops: ``answer-b``, ``true``.
    - LowSignal drops: ``not``, ``a-literal-is-just``,
      ``pitfall-mdash-target-class``.
    - InstructionalArtifact drops: ``submission-format``.
    - LearningObjective drops: ``to-04``.

    Edges intentionally cross domain ↔ noise boundaries so we can
    verify dangling-endpoint pruning.
    """
    return {
        "kind": "concept",
        "nodes": [
            {"id": "rdf-graph", "label": "RDF Graph", "frequency": 8},
            {"id": "blank-node", "label": "Blank Node", "frequency": 5},
            {"id": "sparql-select", "label": "SPARQL SELECT", "frequency": 4},
            {"id": "turtle", "label": "Turtle", "frequency": 6},
            {"id": "key-takeaway", "label": "Key Takeaway", "frequency": 32},
            {"id": "rubric", "label": "Rubric", "frequency": 12},
            {"id": "answer-b", "label": "Answer B", "frequency": 6},
            {"id": "true", "label": "True", "frequency": 4},
            {"id": "not", "label": "Not", "frequency": 8},
            {"id": "a-literal-is-just", "label": "A Literal Is Just", "frequency": 2},
            {"id": "pitfall-mdash-target-class", "label": "Pitfall Mdash Target Class", "frequency": 3},
            {"id": "submission-format", "label": "Submission Format", "frequency": 5},
            {"id": "to-04", "label": "To 04", "frequency": 7},
        ],
        "edges": [
            # Clean domain↔domain (must survive).
            {"source": "rdf-graph", "target": "blank-node", "weight": 4, "relation_type": "co-occurs"},
            {"source": "rdf-graph", "target": "sparql-select", "weight": 3, "relation_type": "co-occurs"},
            {"source": "turtle", "target": "rdf-graph", "weight": 2, "relation_type": "co-occurs"},
            # Mixed: domain ↔ noisy (must be dropped).
            {"source": "rdf-graph", "target": "key-takeaway", "weight": 5, "relation_type": "co-occurs"},
            {"source": "blank-node", "target": "rubric", "weight": 2, "relation_type": "co-occurs"},
            {"source": "answer-b", "target": "true", "weight": 1, "relation_type": "co-occurs"},
            # Both noisy (must be dropped).
            {"source": "key-takeaway", "target": "rubric", "weight": 4, "relation_type": "co-occurs"},
            {"source": "not", "target": "a-literal-is-just", "weight": 1, "relation_type": "co-occurs"},
            {"source": "submission-format", "target": "to-04", "weight": 3, "relation_type": "co-occurs"},
        ],
        "generated_at": "2026-04-24T00:00:00",
    }


def _write_stub(graph_dir: Path, *, semantic_too: bool = True) -> None:
    graph_dir.mkdir(parents=True, exist_ok=True)
    graph = _stub_graph()
    (graph_dir / "concept_graph.json").write_text(
        json.dumps(graph, indent=2), encoding="utf-8"
    )
    if semantic_too:
        # Reuse the same shape; the script handles both files identically.
        (graph_dir / "concept_graph_semantic.json").write_text(
            json.dumps(graph, indent=2), encoding="utf-8"
        )


# ---------------------------------------------------------------------------
# Tests
# ---------------------------------------------------------------------------

def test_clean_course_drops_noisy_nodes(tmp_path):
    course_dir = tmp_path / "stub-course"
    _write_stub(course_dir / "graph", semantic_too=False)

    report = cleaner.clean_course(course_dir)

    assert len(report["graphs"]) == 1
    g = report["graphs"][0]

    # 13 nodes in stub; 4 DomainConcept survive.
    assert g["nodes_before"] == 13
    assert g["nodes_after"] == 4

    # Class breakdown: 9 dropped split as
    # PedagogicalMarker=2, AssessmentOption=2, LowSignal=3,
    # InstructionalArtifact=1, LearningObjective=1.
    dropped = g["dropped_class_counts"]
    assert dropped.get("PedagogicalMarker") == 2
    assert dropped.get("AssessmentOption") == 2
    assert dropped.get("LowSignal") == 3
    assert dropped.get("InstructionalArtifact") == 1
    assert dropped.get("LearningObjective") == 1

    # Kept = DomainConcept only.
    assert g["kept_class_counts"] == {"DomainConcept": 4}


def test_clean_course_drops_dangling_edges(tmp_path):
    course_dir = tmp_path / "stub-course"
    _write_stub(course_dir / "graph", semantic_too=False)

    report = cleaner.clean_course(course_dir)
    g = report["graphs"][0]

    # 9 edges in stub, 3 are clean domain↔domain → 6 dropped via
    # dangling endpoint.
    assert g["edges_before"] == 9
    assert g["edges_after"] == 3
    assert g["edges_dropped"] == 6


def test_clean_course_writes_in_place_with_backup(tmp_path):
    course_dir = tmp_path / "stub-course"
    graph_dir = course_dir / "graph"
    _write_stub(graph_dir, semantic_too=False)
    cleaner.clean_course(course_dir)

    target = graph_dir / "concept_graph.json"
    backup = graph_dir / f"concept_graph.json{cleaner.BACKUP_SUFFIX}"

    # Backup created.
    assert backup.is_file()

    # Backup carries the original 13-node payload.
    bak_payload = json.loads(backup.read_text())
    assert len(bak_payload["nodes"]) == 13

    # In-place file shows the cleaned 4-node payload.
    new_payload = json.loads(target.read_text())
    assert len(new_payload["nodes"]) == 4
    new_ids = {n["id"] for n in new_payload["nodes"]}
    assert new_ids == {"rdf-graph", "blank-node", "sparql-select", "turtle"}


def test_clean_course_handles_both_graph_files(tmp_path):
    course_dir = tmp_path / "stub-course"
    _write_stub(course_dir / "graph", semantic_too=True)

    report = cleaner.clean_course(course_dir)

    # Both ``concept_graph.json`` and ``concept_graph_semantic.json``
    # processed.
    assert len(report["graphs"]) == 2
    paths = [g["path"] for g in report["graphs"]]
    assert any(p.endswith("concept_graph.json") for p in paths)
    assert any(p.endswith("concept_graph_semantic.json") for p in paths)


def test_clean_course_dry_run_does_not_write(tmp_path):
    course_dir = tmp_path / "stub-course"
    graph_dir = course_dir / "graph"
    _write_stub(graph_dir, semantic_too=False)

    target = graph_dir / "concept_graph.json"
    backup = graph_dir / f"concept_graph.json{cleaner.BACKUP_SUFFIX}"
    original = target.read_text()

    cleaner.clean_course(course_dir, dry_run=True)

    # No backup created; target unchanged.
    assert not backup.exists()
    assert target.read_text() == original


def test_clean_course_handles_missing_graph_dir(tmp_path):
    """No ``graph/`` subdir → FileNotFoundError, not silent pass."""
    course_dir = tmp_path / "no-graph"
    course_dir.mkdir()
    with pytest.raises(FileNotFoundError):
        cleaner.clean_course(course_dir)


def test_clean_course_skips_missing_files_gracefully(tmp_path, capsys):
    """``concept_graph_semantic.json`` is OPTIONAL; missing → skip
    with a stderr notice, not a crash."""
    course_dir = tmp_path / "stub-course"
    _write_stub(course_dir / "graph", semantic_too=False)
    # Only concept_graph.json exists; concept_graph_semantic.json is
    # absent.
    report = cleaner.clean_course(course_dir)

    err = capsys.readouterr().err
    assert "concept_graph_semantic.json not present" in err
    assert len(report["graphs"]) == 1


def test_clean_course_report_shape(tmp_path):
    """Report shape matches what the CLI ``_print_report`` consumes."""
    course_dir = tmp_path / "stub-course"
    _write_stub(course_dir / "graph", semantic_too=False)
    report = cleaner.clean_course(course_dir)
    g = report["graphs"][0]

    expected_keys = {
        "path", "nodes_before", "nodes_after", "edges_before",
        "edges_after", "edges_dropped", "dropped_class_counts",
        "kept_class_counts", "dropped_examples",
    }
    assert expected_keys.issubset(g.keys())


def test_print_report_runs_without_error(tmp_path, capsys):
    course_dir = tmp_path / "stub-course"
    _write_stub(course_dir / "graph", semantic_too=False)
    report = cleaner.clean_course(course_dir, dry_run=True)

    cleaner._print_report(report)
    out = capsys.readouterr().out
    # Sanity: the report mentions before/after counts and class names.
    assert "nodes:" in out
    assert "edges:" in out
    assert "DomainConcept" in out
    assert "PedagogicalMarker" in out


def test_main_with_dry_run_returns_zero(tmp_path):
    course_dir = tmp_path / "stub-course"
    _write_stub(course_dir / "graph", semantic_too=False)
    rc = cleaner.main(["--course-dir", str(course_dir), "--dry-run"])
    assert rc == 0


def test_keeps_legitimate_domain_concepts(tmp_path):
    """The script must NEVER drop a DomainConcept-classified node."""
    course_dir = tmp_path / "stub-course"
    graph_dir = course_dir / "graph"
    graph_dir.mkdir(parents=True)
    # All nodes are clean domain vocabulary. Expect zero drops.
    graph = {
        "kind": "concept",
        "nodes": [
            {"id": "rdf-graph", "label": "RDF Graph", "frequency": 5},
            {"id": "owl-2-rl", "label": "OWL 2 RL", "frequency": 3},
            {"id": "shape-constraint", "label": "Shape Constraint", "frequency": 2},
        ],
        "edges": [
            {"source": "rdf-graph", "target": "owl-2-rl", "weight": 2, "relation_type": "co-occurs"},
        ],
        "generated_at": "2026-04-24T00:00:00",
    }
    (graph_dir / "concept_graph.json").write_text(json.dumps(graph, indent=2))

    report = cleaner.clean_course(course_dir)
    g = report["graphs"][0]

    assert g["nodes_before"] == 3
    assert g["nodes_after"] == 3
    assert g["edges_before"] == 1
    assert g["edges_after"] == 1
    assert g["dropped_class_counts"] == {}
