"""
Trainforge - Assessment-Based RAG Training for IMSCC Packages

Trainforge consumes IMSCC packages generated by Courseforge and creates
validated retrieval and training artifacts through assessment-based RAG.

Core capabilities:
- IMSCC package parsing and content extraction
- Learning objective alignment
- Assessment question generation with Bloom's taxonomy targeting
- Comprehensive decision capture for model training and evaluation
- Quality validation with feedback loops
"""

__version__ = "0.1.0"
__author__ = "Ed4All"

from pathlib import Path

PROJECT_DIR = Path(__file__).resolve().parent
