"""Match arXiv PDF bookmarks to IR section headings → page ranges.

arXiv PDFs generated by pdflatex + hyperref usually carry bookmarks that
correspond to \\section commands. Matching these to the IR's h2 headings
lets us extract features from just that section's pages, so per-section
pairs stay under the training context budget.

Coverage is partial — roughly half of local arXiv PDFs have usable
bookmarks. Papers without bookmarks fall back to whole-paper pairs.
"""
from __future__ import annotations

import re
from pathlib import Path

import pypdfium2 as pdfium

from . import ir


def get_pdf_bookmarks(pdf_path: Path) -> list[tuple[str, int]]:
    """Return [(title, 0-indexed-page), ...] for top-level (L0) bookmarks.

    We only consider level-0 bookmarks — these correspond to LaTeX \\section
    commands, which match IR h2 headings. Nested bookmarks (subsections)
    would confuse the per-section split and aren't worth the complexity.
    """
    try:
        pdf = pdfium.PdfDocument(str(pdf_path))
    except Exception:
        return []
    out: list[tuple[str, int]] = []
    for b in pdf.get_toc():
        if b.level != 0:
            continue
        title = b.get_title() or ""
        dest = b.get_dest()
        if dest is None:
            continue
        page = dest.get_index()
        if page is None:
            continue
        out.append((title.strip(), page))
    return out


def section_page_ranges(
    section_titles: list[str],
    bookmarks: list[tuple[str, int]],
    total_pages: int,
) -> dict[str, tuple[int, int]]:
    """Map each IR section title to a (start_page, end_page) range.

    Matching is fuzzy: bookmark titles often have a leading section number
    (e.g. "1. Introduction") that the IR doesn't. We normalize both sides
    before comparing. A section without a bookmark match is omitted — the
    caller decides to skip that section or emit it against the whole PDF.
    """
    normalized_bookmarks = [(_normalize(t), page) for t, page in bookmarks]

    # Pre-compute end pages: each bookmark's range ends where the next one begins.
    bookmark_pages = sorted({page for _, page in bookmarks})
    bookmark_pages.append(total_pages)
    # For each bookmark page, the range ends at the next distinct page.
    end_of = {
        p: bookmark_pages[i + 1]
        for i, p in enumerate(bookmark_pages[:-1])
    }

    ranges: dict[str, tuple[int, int]] = {}
    for title in section_titles:
        norm = _normalize(title)
        start = _fuzzy_lookup(norm, normalized_bookmarks)
        if start is None:
            continue
        ranges[title] = (start, end_of.get(start, total_pages))
    return ranges


_SECTION_PREFIX = re.compile(r"^\s*\d+(?:\.\d+)*\.?\s+")
_NONWORD = re.compile(r"[^a-z0-9 ]")


def _normalize(s: str) -> str:
    """Lowercase, strip leading section numbers, collapse non-word chars."""
    t = s.lower()
    t = _SECTION_PREFIX.sub("", t)
    t = _NONWORD.sub(" ", t)
    return " ".join(t.split())


def _fuzzy_lookup(needle: str,
                  normalized_bookmarks: list[tuple[str, int]]) -> int | None:
    """Return the page of the bookmark best matching `needle`, or None.

    Exact match wins. Otherwise, we accept a bookmark whose normalized title
    is a prefix of the needle (or vice versa) — handles cases like IR having
    "Introduction and Background" while the bookmark is just "Introduction".
    """
    if not needle:
        return None
    for bm_title, page in normalized_bookmarks:
        if bm_title == needle:
            return page
    for bm_title, page in normalized_bookmarks:
        if bm_title and (bm_title in needle or needle in bm_title):
            return page
    return None


def split_paper_into_sections(
    doc: ir.Document,
    pdf_path: Path,
) -> list[tuple[ir.Document, tuple[int, int] | None]]:
    """Split an arXiv paper into (section_doc, page_range) pairs.

    Returns whole-paper fallback as [(doc, None)] when the PDF has no
    usable bookmarks or no section matched. Callers use page_range=None
    to mean "use the whole PDF".
    """
    pdf = pdfium.PdfDocument(str(pdf_path))
    total_pages = len(pdf)
    bookmarks = get_pdf_bookmarks(pdf_path)

    section_docs = ir.split_at_level(doc, split_level=2)
    if not section_docs or not bookmarks:
        return [(doc, None)]

    # Pull each section's title (the text after "<article>: ") for matching.
    titles_for_match: list[str] = []
    for sd in section_docs:
        # split_at_level names the lead doc as the article title alone
        # (no em-dash). Everything else is "Article — Section Name".
        if " — " in sd.title:
            titles_for_match.append(sd.title.split(" — ", 1)[1])
        else:
            titles_for_match.append("Lead")

    ranges = section_page_ranges(titles_for_match, bookmarks, total_pages)

    out: list[tuple[ir.Document, tuple[int, int] | None]] = []
    matched = False
    for sd, title in zip(section_docs, titles_for_match):
        rng = ranges.get(title)
        if rng is not None:
            matched = True
            out.append((sd, rng))
        # Sections we couldn't match are simply dropped — better to lose
        # that section than mis-pair it with the wrong page range.

    if not matched:
        return [(doc, None)]
    return out
